### ISSUE TITLE
exception when try to load more than 25 resumes

### ISSUE THREAD

**Issue by suhasdatascientist** [OmkarPathak/ResumeParser#12] opened 2019-05-09 12:32 UTC
Hello Omkar, I am getting error like this

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "resume_parser/resume_parser.py", line 80, in <module>
    results = [p.get() for p in results]
  File "resume_parser/resume_parser.py", line 80, in <listcomp>
    results = [p.get() for p in results]
  File "C:\Users\EDUBRIDGE\.conda\envs\resume_parser_working\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
IndexError: list index out of range

**Comment by OmkarPathak** [comment] 2019-05-10 03:34
@suhasdatascientist Hi, I tried running the parser with 39 resumes and it works fine. I am not able to reproduce the error. Can you please provide the Python version, OS version so that I can look into this?

**Comment by suhasdatascientist** [comment] 2019-05-10 03:35
Windows10 , Python 3.6

**Comment by suhasdatascientist** [comment] 2019-05-10 03:36
Which version u r using ?

**Comment by OmkarPathak** [comment] 2019-05-10 03:38
@suhasdatascientist I am using Win10 and Python 3.7. But I have tested this on each Python version > 3.5

**Comment by suhasdatascientist** [comment] 2019-05-10 03:39
Could u please share the folder the one you r r running right now

**Comment by OmkarPathak** [comment] 2019-05-10 03:41
I can't share my folder here

**Comment by suhasdatascientist** [comment] 2019-05-10 03:42
OK no worries, will check myself and let you know further

**Comment by OmkarPathak** [comment] 2019-05-10 03:43
According to [this](https://stackoverflow.com/questions/22790672/pool-map-from-multiprocessing-raises-indexerror) post, we are getting an exception internally in `multiprocessing` lib. May be one of your resumes are not getting parsed properly. Can you try on a smaller dataset once?

**Comment by suhasdatascientist** [comment] 2019-05-10 03:46
Sure will check and update

**Comment by suhasdatascientist** [comment] 2019-05-14 03:20
pfa the resumes

**Comment by OmkarPathak** [comment] 2019-06-01 03:21
@suhasdatascientist closing this issue as we were able to parse close to 700 resumes without any error

**Closed by OmkarPathak** 2019-06-01 03:21 UTC
