### ISSUE TITLE
ValueError: Table django_admin_log does not exist

### ISSUE THREAD

**Issue by goyalnikhil02** [OmkarPathak/ResumeParser#10] opened 2019-03-20 12:17 UTC
while using the docker-compose up -d build .I find this error

ERROR: No such service: build

So i use the below command:But still i am facing issue. Please help

user:/home/user/Downloads/ResumeParser-master/resume_parser# docker build .
Sending build context to Docker daemon  393.7kB
.......

[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
Removing intermediate container c2e9af2cebb0
 ---> 3ad6c7dd7482
Step 9/11 : RUN python /usr/src/app/manage.py flush --no-input
 ---> Running in a095170ee199
Traceback (most recent call last):
  File "/usr/src/app/manage.py", line 15, in <module>

File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/introspection.py", line 187, in get_primary_key_column
    raise ValueError("Table %s does not exist" % table_name)
ValueError: Table django_admin_log does not exist
The command '/bin/sh -c python /usr/src/app/manage.py flush --no-input' returned a non-zero code: 1

**Comment by OmkarPathak** [comment] 2019-03-20 14:14
You get this error: `ERROR: No such service: build` This is because you ran `docker-compose up -d build .`. The right command is: `docker-compose up -d build` (notice there is no full stop at the end)

**Comment by goyalnikhil02** [comment] 2019-03-25 12:35
I think the issue is not related to "."
Issue is related to Table django_admin_log does not exist. 
The command '/bin/sh -c python /usr/src/app/manage.py flush --no-input' returned a non-zero code: 1
In manage.py you have written the solution ,but not working .

**Comment by goyalnikhil02** [comment] 2019-03-25 12:59
In place of  "docker-compose up -d build" command  >>  docker-compose up -d web

as in docker-compose file services:web

services:
  web:
    build: ./resume_parser
    command: gunicorn resume_parser.wsgi:application --bind 0.0.0.0:8000


Please correct me if i am wrong.

**Comment by OmkarPathak** [comment] 2019-03-25 13:12
@goyalnikhil02 are you running docker on windows or linux?

**Comment by OmkarPathak** [comment] 2019-03-26 08:46
@goyalnikhil02 I was now able to reproduce the issue. You can see the changes here: [Changes](https://github.com/OmkarPathak/ResumeParser/commit/612ba88e9636faeace19caaef620c0eeb0049a6c)

**Comment by OmkarPathak** [comment] 2019-03-27 01:23
@goyalnikhil02 do let me know if you are able to resolve the issue so that I can mark this issue as close :smile:

**Comment by goyalnikhil02** [comment] 2019-03-27 05:35
@OmkarPathak  docker image is running now , but on upload any resume  giving the error.


Request Method: | POST
-- | --
http://ip/
2.1.5
OperationalError
no such table: parser_app_resume
/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py in execute, line 298
/usr/local/bin/python
3.7.2
['/usr/src/app',  '/usr/local/bin',  '/usr/local/lib/python37.zip',  '/usr/local/lib/python3.7',  '/usr/local/lib/python3.7/lib-dynload',  '/usr/local/lib/python3.7/site-packages']
Wed, 27 Mar 2019 05:34:24 +0000

**Comment by OmkarPathak** [comment] 2019-03-27 09:57
@goyalnikhil02  try changing 
```
RUN python /usr/src/app/manage.py migrate
```

to this

```
RUN python /usr/src/app/manage.py migrate --no-input
```

in `Dockerfile`

**Comment by OmkarPathak** [comment] 2019-04-20 03:10
@goyalnikhil02 any leads? Should I close this issue?

**Closed** 2019-04-27 06:42 UTC
